USE TEAMSEAS;
SHOW TABLES;

-- OPPGAVE #1
SELECT * FROM VOLUNTEER;

-- OPPGAVE #2
SELECT FIRSTNAME FROM VOLUNTEER;

-- OPPGAVE #3 
SELECT * FROM ARRANGEMENTS;

-- OPPGAVE #4
SELECT * FROM volunteer_info_has_arrangements WHERE ArrangementID = 1;
SELECT * FROM VOLUNTEER WHERE IDVOLUNTEER = 1 OR IDVOLUNTEER = 7;

-- OPPGAVE #5: Select all Arrangements that is happening in 2025.
SELECT * FROM ARRANGEMENTS WHERE ARRANGEMENTDATE < '2026-01-01';